### ISSUE TITLE
모임 검색 리팩토링

### ISSUE THREAD

**Issue by java-saeng** [YAPP-Github/20th-iOS-Team-1-BE#125]
### Description
- 모임 검색 관련 api 리팩토링

### To-Be
- 객체지향적으로 모임 검색 관련 api를 리팩토링할 수 있다

### Todo
- [ ] 반환할 DTO 중복 제거
- [x] 검색 조건들 validation 추가
- [ ] 불필요한 쿼리 제거
