### ISSUE TITLE
test container를 이용하여 통합 테스트 구성

### ISSUE THREAD

**Issue by java-saeng** [YAPP-Github/20th-iOS-Team-1-BE#147]
### Description
- test container 를 이용하여 독립적인 테스트 환경 구성

### To-Be
- test container를 이용하여 테스트 멱등성을 보장할 수 있다
- test container를 이용하여 로컬에서도 도커만 설치하여 테스트를 구동할 수 있다

### Todo
- [x] test container 공부
- [x] test container 핵심 로직을 익히기 위해 토이 프로젝트
- [x] test를 작성하고, 해당 프로젝트에 test container 적용
