### ISSUE TITLE
DB Replication을 통한 read/write DB 분리

### ISSUE THREAD

**Issue by znftm97** [YAPP-Github/20th-iOS-Team-1-BE#174]
### Description
- AWS Aurora를 활용하여 DB Replication을 수행합니다.
- Read용 DB와 Wirte용 DB를 분리합니다.

### To-Be
- 스프링 @Transactional readOnly 옵션에따라 Primary DB와 Secondary DB 커넥션을 획득할 수 있다.

### Todo
- [x] AWS Aurora 생성
- [x] 기존 RDS 데이터 덤프
- [x] 애플리케이션 DataSoruce 설정

### Blog Link
[CQS 패턴 적용 및 read/write DB 분리하기 - AWS Aurora](https://velog.io/@znftm97/CQS-%ED%8C%A8%ED%84%B4-%EC%A0%81%EC%9A%A9-%EB%B0%8F-readwrite-DB-%EB%B6%84%EB%A6%AC%ED%95%98%EA%B8%B0-AWS-Aurora)
