### ISSUE TITLE
sql 파일 추가 및 리팩토링

### ISSUE THREAD

**Issue by znftm97** [YAPP-Github/20th-iOS-Team-1-BE#32]
### Description
테스트코드를 위한 data.sql 파일을 적용 및 이로인한 테스트 코드 리팩토링 진행,
추가로 커스텀 어노테이션 적용으로 인한 로직 수정 진행 

### To-Be
- data.sql 파일을 이용한 테스트 코드 작성 가능
- 커스텀 어노테이션 적용

### Todo
- [ ] data.sql 파일 적용
- [ ] 커스텀 어노테이션 적용
- [ ] 테스트 코드 수정
