### ISSUE TITLE
모임 참여, 나가기, 삭제 API

### ISSUE THREAD

**Issue by znftm97** [YAPP-Github/20th-iOS-Team-1-BE#73]
### Description
- 모임을 참여 또는 나간다.
- 모임을 삭제한다.

### To-Be
- 모임에 인원이 비어있으면 참여할 수 있다.
- 참여중인 모임을 나갈 수 있다.
- 방장이 모임을 나가도, 모임은 유지된다.
- 방장은 모임을 삭제할 수 있다.

### Todo
- [x] 모임 참여 API 개발
- [x] 모임 나가기 API 개발
- [x] 모임 삭제 API 개발
